// GOYA website content — events, stats, gallery.
// To add an event, copy one block below. Set `ticketUrl` when tickets go live.
const P = "/assets/photos/";

export const DATA = {
  events: [
    {
      id: "anastasia",
      year: 2026,
      day: "02",
      month: "OCT",
      dow: "FRI",
      time: "Time TBA",
      category: "Concert",
      tone: "accent",
      free: false,
      title: "Anastasia Concert",
      venue: "The Greek Club, Brisbane",
      photo: P + "anastasia-tour.jpg",
      photoPos: "top",
      blurb:
        "The GOYA Weekend opens with Anastasia, live in Brisbane as part of her Australian Tour — the kick-off to three days of glendi. Tickets and times still to be announced — watch this space.",
      tags: ["GOYA Weekend", "Social", "Concert"],
      ticketUrl: null,
    },
    {
      id: "aegean-cup",
      updatesUrl: "https://instagram.com/aegeancup",
      year: 2026,
      day: "03",
      month: "OCT",
      dow: "SAT",
      time: "12:00 PM",
      category: "Sports",
      tone: "sand",
      free: false,
      title: "Aegean Cup",
      venue: "Olympic FC, Brisbane",
      photo: P + "aegean-cup.jpg",
      blurb:
        "Our weekend football comp, run with the Kos community of Brisbane — 8 teams representing the Greek islands, 2 groups, 1 champion. Teams, trophies and plenty of filotimo. Interstate parea, this one is well worth the trip. Follow @aegeancup for the draw and updates.",
      tags: ["GOYA Weekend", "Sports"],
      ticketUrl: null,
    },
    {
      id: "kefi-night",
      year: 2026,
      day: "03",
      month: "OCT",
      dow: "SAT",
      time: "Time TBA",
      category: "Social",
      tone: "accent",
      free: false,
      title: "Kefi Night",
      venue: "Venue TBA",
      photo: P + "kefi-night.jpg",
      blurb:
        "Pure kefi — music, dancing and good company late into the night. The Saturday of the GOYA Weekend you won’t want to miss. Details to be announced.",
      tags: ["GOYA Weekend", "Social"],
      ticketUrl: null,
    },
    {
      id: "gazi-night",
      year: 2026,
      day: "04",
      month: "OCT",
      dow: "SUN",
      time: "Time TBA",
      category: "Social",
      tone: "accent",
      free: false,
      title: "Gazi Club Night",
      venue: "Venue TBA",
      photo: P + "gazi-night.jpg",
      blurb:
        "We send the GOYA Weekend out in true Gazi style — a proper club night to close three days of parea. Details to be announced.",
      tags: ["GOYA Weekend", "Social"],
      ticketUrl: null,
    },
  ],
  filters: ["All", "GOYA Weekend", "Social", "Sports", "Concert"],
  stats: [
    { value: "120+", label: "Active members" },
    { value: "40+", label: "Events a year" },
    { value: "Fri", label: "Open every week" },
  ],
  gallery: [
    {
      src: P + "goya-crowd.jpg",
      alt: "Friends dancing together at a GOYA night",
      caption: "Together, after dark.",
    },
    {
      src: P + "goya-singer.jpg",
      alt: "A singer performing live for the GOYA crowd",
      caption: "One more song.",
    },
    {
      src: P + "goya-banner-team.jpg",
      alt: "GOYA members with the banner on the verandah",
      caption: "At home with the parea.",
    },
    {
      src: P + "goya-flag.jpg",
      alt: "An illuminated Greek flag on the wall at a GOYA gathering",
      caption: "Our roots, carried forward.",
    },
    {
      src: P + "junior-goya.jpg",
      alt: "Junior GOYA together at the skating rink",
      caption: "Little parea. Big memories.",
    },
    {
      src: P + "goya-team.jpg",
      alt: "GOYA friends gathered together",
      caption: "The people make the place.",
    },
  ],
};
