// GOYA website content — events, stats, gallery.
// To add an event, copy one block below. Set `ticketUrl` when tickets go live.
const P = "/assets/photos/";

export const DATA = {
  events: [
    {
      id: "anastasia-meet-and-greet", year: 2026, day: "01", month: "OCT", dow: "THU",
      time: "5 PM–7 PM", category: "Social", title: "Meet Anastasia",
      venue: "Cyprus House, 4 Vulture Street, West End",
      photo: P + "anastasia-tour.jpg", photoPos: "top",
      blurb: "Welcome Anastasia to Brisbane before Friday’s concert. Join GOYA and Brisbane’s Greek and Cypriot associations at Cyprus House for a meet-and-greet on Thursday 1 October, from 5pm to 7pm.",
      tags: ["GOYA Weekend", "Social"], ticketUrl: null,
      updatesUrl: "https://www.instagram.com/goya.brisbane/p/Dd0OjR_z13Y/",
      entryNote: "See the official announcement for the latest event information.",
    },
    {
      id: "anastasia",
      featured: true,
      updatesUrl: "https://www.instagram.com/goya.brisbane/p/DcubarZTZ3K/",
      entryNote: "See the organiser’s announcement for booking enquiries. A start time and direct ticket link have not been verified.",
      year: 2026,
      day: "02",
      month: "OCT",
      dow: "FRI",
      time: "Time TBA",
      category: "Concert",
      tone: "accent",
      free: false,
      title: "Anastasia Concert",
      venue: "The Greek Club, Brisbane",
      photo: P + "anastasia-tour.jpg",
      photoPos: "top",
      blurb:
        "Anastasia performs live in Brisbane on Friday 2 October at The Greek Club, opening the GOYA Weekend. Follow GOYA Brisbane for the latest start time and ticket details.",
      tags: ["GOYA Weekend", "Social", "Concert"],
      ticketUrl: null,
    },
    {
      id: "aegean-cup",
      featured: true,
      entryNote: "Gates open at 11:30am. Matches begin at noon; the grand final is scheduled for 7pm, followed by trophy presentations at 7:50pm.",
      updatesUrl: "https://www.instagram.com/aegeancup/p/DdlCmznvO72/",
      year: 2026,
      day: "03",
      month: "OCT",
      dow: "SAT",
      time: "Gates 11:30 AM · Kick-off 12 PM",
      category: "Sports",
      tone: "sand",
      free: false,
      title: "Aegean Cup",
      venue: "Olympic FC, Goodwin Park, Yeronga",
      photo: P + "aegean-cup.jpg",
      blurb:
        "Our weekend football comp, run with the Kos community of Brisbane — 8 teams representing the Greek islands, 2 groups, 1 champion. Teams, trophies and plenty of filotimo. Interstate parea, this one is well worth the trip. Follow @aegeancup for the draw and updates.",
      tags: ["GOYA Weekend", "Sports"],
      ticketUrl: null,
    },
    {
      id: "aegean-cup-after-party",
      featured: true,
      updatesUrl: "https://www.instagram.com/goya.brisbane/p/Dd00R6VTz9B/",
      age: "18+ only",
      entryNote: "18+ only. See the official announcement for the latest entry information.",
      year: 2026,
      day: "03",
      month: "OCT",
      dow: "SAT",
      time: "9 PM until late",
      category: "Social",
      tone: "accent",
      free: false,
      title: "Aegean Cup After Party",
      venue: "Olympic FC Function Hall, Yeronga",
      photo: P + "kefi-night.jpg",
      blurb:
        "The Aegean Cup continues after the final whistle. Join the parea for the Aegean Cup After Party on Saturday 3 October. Head to Olympic FC Function Hall from 9pm for a night with Brisbane’s Greek community. This event is strictly 18+.",
      tags: ["GOYA Weekend", "Social"],
      ticketUrl: null,
    },

  ],
  filters: ["All", "GOYA Weekend", "Social", "Sports", "Concert"],
  stats: [
    { value: "120+", label: "Active members" },
    { value: "40+", label: "Events a year" },
    { value: "Fri", label: "Open every week" },
  ],
  gallery: [
    {
      src: P + "goya-crowd.jpg",
      alt: "Friends dancing together at a GOYA night",
      caption: "Together, after dark.",
    },
    {
      src: P + "goya-singer.jpg",
      alt: "A singer performing live for the GOYA crowd",
      caption: "One more song.",
    },
    {
      src: P + "goya-banner-team.jpg",
      alt: "GOYA members with the banner on the verandah",
      caption: "At home with the parea.",
    },
    {
      src: P + "goya-flag.jpg",
      alt: "An illuminated Greek flag on the wall at a GOYA gathering",
      caption: "Our roots, carried forward.",
    },
    {
      src: P + "junior-goya.jpg",
      alt: "Junior GOYA together at the skating rink",
      caption: "Little parea. Big memories.",
    },
    {
      src: P + "goya-team.jpg",
      alt: "GOYA friends gathered together",
      caption: "The people make the place.",
    },
  ],
};
